export const FETCH_LIST_BOOKING_JOBS_REQUEST  = "@fetchListBookingJobsReducer/FETCH_LIST_BOOKING_JOBS_REQUEST";
export const FETCH_LIST_BOOKING_JOBS_SUCCESS = "@fetchListBookingJobsReducer/FETCH_LIST_BOOKING_JOBS_SUCCESS";
export const FETCH_LIST_BOOKING_JOBS_FAILED = "@fetchListBookingJobsReducer/FETCH_LIST_BOOKING_JOBS_FAILED";

// export const FETCH_DETAIL_USER_BOOKING_REQUEST  = "@fetchListBookingJobsReducer/FETCH_DETAIL_USER_BOOKING_REQUEST";
// export const FETCH_DETAIL_USER_BOOKING_SUCCESS = "@fetchListBookingJobsReducer/FETCH_DETAIL_USER_BOOKING_SUCCESS";
// export const FETCH_DETAIL_USER_BOOKING_FAILED = "@fetchListBookingJobsReducer/FETCH_DETAIL_USER_BOOKING_FAILED";