

export const FETCH_DETAIL_ADMIN_LOGIN_REQUEST  = "@profilePageReducer/FETCH_DETAIL_ADMIN_LOGIN_REQUEST";
export const FETCH_DETAIL_ADMIN_LOGIN_SUCCESS = "@profilePageReducer/FETCH_DETAIL_ADMIN_LOGIN_SUCCESS";
export const FETCH_DETAIL_ADMIN_LOGIN_FAILED = "@profilePageReducer/FETCH_DETAIL_ADMIN_LOGIN_FAILED";

export const ADD_SKILLS_REQUEST  = "@profilePageReducer/ADD_SKILLS_REQUEST";
export const ADD_SKILLS_SUCCESS = "@profilePageReducer/ADD_SKILLS_SUCCESS";
export const ADD_SKILLS_FAILED = "@profilePageReducer/ADD_SKILLS_FAILED";

export const ADD_CERTIFICATIONS_REQUEST  = "@profilePageReducer/ADD_CERTIFICATIONS_REQUEST";
export const ADD_CERTIFICATIONS_SUCCESS = "@profilePageReducer/ADD_CERTIFICATIONS_SUCCESS";
export const ADD_CERTIFICATIONS_FAILED = "@profilePageReducer/ADD_CERTIFICATIONS_FAILED";

