export const ADD_JOBS_REQUEST  = "@addJobsReducer/ADD_JOBS_REQUEST";
export const ADD_JOBS_SUCCESS = "@addJobsReducer/ADD_JOBS_SUCCESS";
export const ADD_JOBS_FAILED = "@addJobsReducer/ADD_JOBS_FAILED";

export const FETCH_LIST_TYPE_JOBS_REQUEST  = "@addJobsReducer/FETCH_LIST_TYPE_JOBS_REQUEST";
export const FETCH_LIST_TYPE_JOBS_SUCCESS = "@addJobsReducer/FETCH_LIST_TYPE_JOBS_SUCCESS";
export const FETCH_LIST_TYPE_JOBS_FAILED = "@addJobsReducer/FETCH_LIST_TYPE_JOBS_FAILED";

export const FETCH_LIST_SUBTYPE_JOBS_REQUEST  = "@addJobsReducer/FETCH_LIST_SUBTYPE_JOBS_REQUEST";
export const FETCH_LIST_SUBTYPE_JOBS_SUCCESS = "@addJobsReducer/FETCH_LIST_SUBTYPE_JOBS_SUCCESS";
export const FETCH_LIST_SUBTYPE_JOBS_FAILED = "@addJobsReducer/FETCH_LIST_SUBTYPE_JOBS_FAILED";